version: '3.1'
 
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: baza
            PGDATA: /data
        ports:
        - "5432:5432"
        volumes:
        - data:/data
        networks:
        - postgres-internal
    admin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: user@user.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 8080
        ports:
        - "8080:8080"
        volumes:
        - data2:/var/lib/pgadmin
        networks:
        - postgres-internal
networks:
    postgres-internal:
        external: false
volumes:
    data:
        driver: local
    data2:
        driver: local
